# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.1.0'
      - run: flutter pub get
      - run: flutter build apk
      # now relase the just created build
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/apk/release/*.apk"
